-- 코드를 입력하세요
-- 조건 1.  자동차 종류가 '세단' 또는 'SUV' 인 자동차 
-- 조건 2. 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 조건 3. 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차 
-- DAILY_FEE *30 (할인 율 -> 1 - DISCOUNT_RATE /100)
-- 조건 4. 30일 이상의 경우 DISCOUNT 생각하기

-- 출력 형태 자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE)
SELECT C.CAR_ID , C.CAR_TYPE, FLOOR(C.DAILY_FEE * 30 * (1-(IFNULL(R.DISCOUNT_RATE,0)/ 100))) AS FEE
FROM  CAR_RENTAL_COMPANY_CAR C LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN R ON C.CAR_TYPE = R.CAR_TYPE
AND DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단' , 'SUV')
AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-30' AND END_DATE >='2022-11-01'
)
AND (C.DAILY_FEE * 30 * (1-(IFNULL(R.DISCOUNT_RATE,0) / 100))) >=500000
AND (C.DAILY_FEE * 30 * (1-(IFNULL(R.DISCOUNT_RATE ,0) / 100))) <= 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;