-- 코드를 작성해주세요
SELECT HR.EMP_NO, HR.EMP_NAME, G.GRADE,
IF(G.GRADE = 'S', HR.SAL * 0.2,
  IF(G.GRADE = 'A', HR.SAL * 0.15,
    IF(G.GRADE = 'B',HR.SAL * 0.1, 0)
      )) AS BONUS
FROM HR_EMPLOYEES AS HR JOIN
(
    SELECT EMP_NO, 
    CASE 
        WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) >= 80 THEN 'B'
    ELSE 'C' END AS GRADE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) AS G ON HR.EMP_NO = G.EMP_NO
ORDER BY HR.EMP_NO;
