-- 코드를 작성해주세요
SELECT
    YEAR(ED.DIFFERENTIATION_DATE) AS YEAR,
    (MAX_E.YEAR_MAX_SIZE - ED.SIZE_OF_COLONY )AS YEAR_DEV,
     ED.ID
FROM ECOLI_DATA ED 
JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS YEAR_MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS MAX_E

ON YEAR(ED.DIFFERENTIATION_DATE) = MAX_E.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;